version: "3"

services:

  web:
    build: ./hold-my-beer
    ports:
      - "4200:4200"
    links:
      - microservice_tables
      - microservice_drinks
      - microservice_users
    volumes:
      - ./hold-my-beer:/usr/src/app
    depends_on:
      - microservice_tables
      - microservice_drinks
      - microservice_users
  
  microservice_tables:
    build: ./micro_service_3
    ports:
      - "3003:3000"
    links:
      - database_tables
    volumes:
      - ./micro_service_3:/usr/src/app
    depends_on:
      - database_tables
  
  database_tables:
    image: mongo
  
  microservice_drinks:
    build: ./micro_service_2
    ports:
      - "3002:3000"
    links:
      - database_drinks
    volumes:
      - ./micro_service_2:/usr/src/app
    depends_on:
      - database_drinks
  
  database_drinks:
    image: mongo
    volumes:
        - type: volume
          source: mongodb_drinks_data_volume
          target: /data/db

  microservice_users:
    build: ./micro_service_1
    ports:
      - "3001:3000"
    links:
      - database_users
    volumes:
      - ./micro_service_1:/usr/src/app
    depends_on:
      - database_users
      
  database_users:
    image: mongo

volumes:
  mongodb_drinks_data_volume:
        external: true